title: Mi Documentación
email: tu-email@example.com
description: >-
  Aquí va una breve descripción de tu documentación.
baseurl: ""
url: ""
github_username: tu-nombre-de-usuario

# No hay línea de "theme" aquí

markdown: kramdown
highlighter: rouge
